# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2018-01-03 21:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseorg',
            name='image',
            field=models.ImageField(upload_to='static/org/%Y/%m', verbose_name='封面图'),
        ),
    ]
