# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-01-12 17:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0004_auto_20180110_1638'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='org/teacher/%Y/%m', verbose_name='封面图'),
        ),
    ]
