# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-01-22 11:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_course_teacher'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='notice',
            field=models.CharField(default='', max_length=50, verbose_name='课程公告'),
        ),
    ]
